#!/usr/bin/env python3
"""Generate the transport chain problems used by the 8.7 experiment.

    scripts/gen_transport_chain.py            # rewrite domains/transport_chain_*.hddl

The instances are deliberately shaped, and the shape is the whole point.

  *One-way* roads city_loc_0 -> city_loc_1 -> ... -> city_loc_{N-1}.

    The shipped transport_problem.hddl has three locations and a complete road
    graph, so m_drive_to_via's `(not (road ?l1 ?l3))` guard never passes and
    the recursion that 8.7 is about never fires. A chain makes it fire. Making
    the chain one-way is what keeps it terminating: this planner's rollouts are
    an unbounded depth-first search with no cycle detection, and on a two-way
    chain the recursion can oscillate between two locations forever. With
    one-way roads every recursive step strictly advances along the chain in
    every one of the four encodings, so each rollout is finite.

  K packages, all at city_loc_1, all destined for city_loc_{N-1}.

    Unordered `deliver` tasks whose get_to subtasks all want the same drives:
    exactly the sharing that makes one plan reachable through many
    decompositions. The truck's capacity is K, so it can carry them all and a
    shortest plan makes a single pass.

Two problem files per size, because the insert encoding needs `free_drive` in
the initial task network and the other three must not have it.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
DOMAINS = os.path.join(os.path.dirname(HERE), "domains")

# (name, locations, packages)
#
# The ladder moves one knob at a time, because the two knobs are supposed to
# enter the redundancy differently. Godet et al. count n^k decompositions of
# one plan, where n is how many goto tasks are unordered with each other and k
# is how many movement actions they have to produce between them. Packages set
# n (two get_to subtasks each); chain length sets k. b is the hub: c adds a
# package to it, d adds a location.
SIZES = [
    ("a", 4, 2),   # 3 drives, 4 get_to
    ("b", 5, 2),   # 4 drives, 4 get_to
    ("c", 5, 3),   # 4 drives, 6 get_to   -- b plus one package
    ("d", 6, 2),   # 5 drives, 4 get_to   -- b plus one location
]


def problem(name, n_loc, n_pkg, insert):
    locs = [f"city_loc_{i}" for i in range(n_loc)]
    pkgs = [f"package_{i}" for i in range(n_pkg)]
    caps = [f"capacity_{i}" for i in range(n_pkg + 1)]
    dest = locs[-1]

    objects = "\n".join(f"\t\t{p} - package" for p in pkgs)
    objects += "\n" + "\n".join(f"\t\t{c} - capacity_number" for c in caps)
    objects += "\n" + "\n".join(f"\t\t{l} - location" for l in locs)
    objects += "\n\t\ttruck_0 - vehicle"

    subtasks = [f"\t\t (task{i} (deliver {p} {dest}))" for i, p in enumerate(pkgs)]
    if insert:
        # One free_drive per vehicle, unordered with respect to everything.
        subtasks.append(f"\t\t (task{len(pkgs)} (free_drive truck_0))")

    init = [f"\t\t(capacity_predecessor {caps[i]} {caps[i+1]})" for i in range(n_pkg)]
    init += [f"\t\t(road {locs[i]} {locs[i+1]})" for i in range(n_loc - 1)]
    init += [f"\t\t(at {p} {locs[1]})" for p in pkgs]
    init += [f"\t\t(dest {p} {dest})" for p in pkgs]
    init.append(f"\t\t(at truck_0 {locs[0]})")
    init.append(f"\t\t(capacity truck_0 {caps[-1]})")

    return f"""; Generated by scripts/gen_transport_chain.py -- do not edit by hand.
; {n_loc} locations in a one-way chain, {n_pkg} packages from {locs[1]} to {dest}.
; A shortest plan needs {n_loc - 1} drives.
(define
\t(problem chain_{name}{'_insert' if insert else ''})
\t(:domain  transport_variant)
\t(:objects
{objects}
\t)
\t(:htn
\t\t:parameters ()
\t\t:subtasks (and
{chr(10).join(subtasks)}
\t\t)
\t)
\t(:init
{chr(10).join(init)}
\t)
)
"""


def main():
    written = []
    for name, n_loc, n_pkg in SIZES:
        for insert in (False, True):
            suffix = "_insert" if insert else ""
            path = os.path.join(DOMAINS, f"transport_chain_{name}{suffix}.hddl")
            with open(path, "w") as f:
                f.write(problem(name, n_loc, n_pkg, insert))
            written.append(os.path.basename(path))
    print("\n".join(written))


if __name__ == "__main__":
    main()
